shiro:
  ws:
    client:
      enable: true
      url: "ws://localhost:3001"
spring:
  profiles:
    #使用 mysql 或 sqlite
    active: sqlite

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: false

#bot 设置
bot-config:
  base:
    #昵称
    nick-name: "布丁"
    #命令前缀
    prefix:
    #主人QQ号
    master:
      - '12345678'
    #代理
    proxy:
      host: "127.0.0.1"
      port: 7890
      type: "HTTP"
  #插件设置
  plugins:
    chat-gpt-config:
      token: ""
      timeout: 30
      module: "gpt-3.5-turbo"
      proxy: true
    aria2-config:
      url: "http://localhost:6800/jsonrpc"
      token: ""
    picSearch-config:
      timeout: 30
      proxy: false
      token:
      alwaysUseAscii2d: true
    tarot-config:
      cd: 60
    steam-config:
      apikey: ""
    word-cloud-config:
      cron-task-rate: 5
      max-font-size: 80
      min-font-size: 20
      filter-rule: [ "http","&#" ]
