spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pudding
    username: root
    password: "root"
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      platform: mysql