server:
  # SpringBoot 项目的运行端口即为客户端反向 Websocket 连接端口
  port: 5555
#spring:
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:BotDB.sqlite3
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
#bot 设置
bot-config:
  nick-name: "布丁"
  bot-id: '10001'
  prefix:
  master:
    - '10001'
  tarot:
    #单位 秒
    cd: 60
  aria2:
    url:
    token:
  pic-search:
    proxy: false
    #单位 秒
    timeout: 60
    token: xxxxxxxxxxxxx
    #相似度低于多少自动调用Ascii2d搜图（自动转为 Float 类型）
    similarity: 60
    #始终使用 Ascii2d 搜图（该设置为 true 时 similarity 不生效）
    alwaysUseAscii2d: false
    #如果是番剧是否发送预览视频
    animePreviewVideo: false